---
# Start role monitoring

- name: Install reverse proxy
  hosts: yc-reverse-nginx
  roles:
    - reverse-proxy-role

- name: Install mysql server
  hosts: yc-mysql
  roles:
    - db-mysql-role

- name: Install apps server
  hosts: yc-apps
  roles:
    - apps-server-role

- name: Install gitlab ci
  hosts: yc-gitlab-ci
  roles:
    - gitlab-ci-role

- name: Install prometheus/grafana/alertmanager
  hosts: all
  roles:
    - monitoring-role